services:
  # resume_generator:
  #   build:
  #     context: .
  #     dockerfile: resume_generator/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./data:/app/data
  #   command: ["uv", "run", "--no-sync", "uvicorn", "resume_generator.main:app", "--host", "0.0.0.0", "--port", "${CV_GENERATOR_PORT}", "--reload"]
  #   ports:
  #     - "${CV_GENERATOR_PORT}:${CV_GENERATOR_PORT}"
  #   restart: always

  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    env_file:
      - .env
    environment:
      AGENT_LLM_API_URL: http://host.docker.internal:${OLLAMA_PORT}/v1
      AGENT_LLM_API_TOKEN: ${AGENT_LLM_API_TOKEN}
      AGENT_LLM_API_MODEL: ${AGENT_LLM_API_MODEL}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["uv", "run", "--no-sync", "uvicorn", "agent.main:app", "--host", "0.0.0.0", "--port", "${AGENT_PORT}", "--reload"]
    ports:
      - "${AGENT_PORT}:${AGENT_PORT}"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      # ollama:
      #   condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AGENT_PORT}/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  data_loader:
    build:
      context: .
      dockerfile: db/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./data/resumes_json:/app/data/resumes_json
    command: ["python", "load_initial_data.py"]
    restart: "on-failure"

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    command: ["streamlit", "run", "streamlit/streamlit_app.py", "--server.port=${STREAMLIT_PORT}"]
    restart: on-failure
    volumes:
      - ./data:/app/data
    ports:
      - "${STREAMLIT_PORT}:${STREAMLIT_PORT}"
    environment:
      AGENT_HOST: agent
      AGENT_PORT: ${AGENT_PORT}
      PYTHONUNBUFFERED: 1
      STREAMLIT_SERVER_HEADLESS: true
      STREAMLIT_SERVER_ENABLECORS: false
    depends_on:
      agent:
        condition: service_healthy

  # ollama:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ~/.ollama:/root/.ollama
  #   ports:
  #     - "${OLLAMA_PORT}:${OLLAMA_PORT}"
  #   env_file:
  #     - .env
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=24h
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   healthcheck:
  #     test: "ollama --version && ollama ps || exit 1"
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s

volumes:
  postgres_data:
