services:
  cv_generator:
    env_file:
      - .env
    build:
      dockerfile: cv_generator/Dockerfile
      context: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cv_generator/:/app/cv_generator/
    command: ["uvicorn", "cv_generator.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - ollama
  ollama:
    volumes:
    - ~/.ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
