services:
  cv_generator:
    env_file:
      - .env
    build:
      dockerfile: src/cv_generator/Dockerfile
      context: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src/cv_generator:/app/src/cv_generator
    command: ["uvicorn", "src.cv_generator.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    restart: always
